### ISSUE TITLE
Error since Revolutions Slider Update to V. 6

### ISSUE THREAD

**Issue by peerfischer** [WPPress/acf-sliders#10]
`Fatal error: Uncaught Error: Call to undefined method RevSliderOutput::putSlider() in /homepages/19/d327232725/htdocs/wp-content/plugins/acf-sliders-master/field-revslider.php:24 Stack trace: #0 /homepages/19/d327232725/htdocs/www.knoer.de/wp-content/plugins/acf-sliders-master/slider.class.php(171): WPPress_RevolutionSlider_ACF_Field->slider_output('1') #1 /homepages/19/d327232725/htdocs/www.knoer.de/wp-includes/class-wp-hook.php(286): WPPress_ACF_Field->format_value('1', 2, Array) #2 /homepages/19/d327232725/htdocs/wp-includes/plugin.php(251): WP_Hook->apply_filters('1', Array) #3 /homepages/19/d327232725/htdocs/wp-content/plugins/advanced-custom-fields-pro/includes/acf-hook-functions.php(101): apply_filters_ref_array('acf/format_valu...', Array) #4 /homepages/19/d327232725/htdocs/wp-includes/class-wp-hook.php(286): _acf_apply_hook_variations('1', 2, Array) #5 /homepages/19/d327232725/htdocs/wp-includes/plugin.php(208): WP_Hook->apply_filters('1', Array) #6 in /homepages/19/d327232725/htdocs/wp-content/plugins/acf-sliders-master/field-revslider.php on line 24`

is there a fix for this issue?

Best!
P.

**Comment by ah-lara** [comment]
Same here. Is there a fix?

**Comment by peerfischer** [comment]
There has been an upadte - but its still not working for me with Revolutions Slider 6 ... is there anyone where this is working now?

**Comment by Natasha717** [comment]
Hi,

This is also a big issue I am experiencing right now. Has anyone managed to reach out to the developers and ask if there is any possibility of an update to this?

Any help would be appreciated.

Thank you.

Tasha

**Comment by pixelatedorange** [comment]
I've got this issue too, so frustrating as having to replace 20 or so sliders with text fields and manually entering the shortcode for each slider.

Really hoping for a fix soon.

**Comment by ssovit** [comment]
Sorry for delays..

I have fixed the issue
