### ISSUE TITLE
Warning on Slider class

### ISSUE THREAD

**Issue by ggoyanes** [WPPress/acf-sliders#11]
Hello! This is not an error but it's causing a lot of noise in logs:

I have this PHP warning:

> PHP Warning:  in_array() expects parameter 2 to be array, boolean given in /[path]/wp-content/plugins/acf-sliders/slider.class.php on line 202

It's a quick fix, just checking if $field['disable'] is an array/not false.

Could this be fixed?

Thank you!!

**Comment by ssovit** [comment]
it should be fixed now
