### ISSUE TITLE
Allow for no slider

### ISSUE THREAD

**Issue by kLOsk** [WPPress/acf-sliders#2]
Currently the drop down in the post editor always shows all sliders available. It would be good if it was also possible to not select any slider, so the plugin would not output anything!
I selected Allow Null in ACF, tho the Post Editor still automatically chooses the first slider. I might create a fix for this myself and make a pull request!

**Comment by kLOsk** [comment]
I just looked into it a bit further and found that the problem lies with the fact that the "allow null" option is not being saved...

**Comment by si-le** [comment]
Hi kLOsk!

Whats about your pull request?
I'm haveing the same problem here, so it wouldt be very nice to be fixed!
Or, plz, can you point me out where i can fix it by myselfe?

Thanks!

**Comment by kLOsk** [comment]
Hi pixselig, I actually just implemented a weak hack to fix it.
In slider.class.php Change line 185 to 188 to:

```
    echo '<select id="' . $field['name'] . '" class="' . $field['class'] . '" name="' . $field['name'] . '" ' . $multiple . ' >';
    echo '<option value="null"> - Select - </option>';
    //if ($field['allow_null'] == '1') {
    //  echo '<option value="null"> - Select - </option>';
    //}
```

Not the ideal way and it prevents you from updating the plugin, tho since I doubt this plugin will see any updates and since they need to be applied manually anyways, I guess it's ok!
