### ISSUE TITLE
Selected doesn't work

### ISSUE THREAD

**Issue by Diesector** [WPPress/acf-sliders#4]
When editing a page with the ACF the "selected" doesn't work.  Hide disabled works, but no matter what I can see that "selected" never gets added to the dropdown.  So if a user resaves the page they could inadvertently and effectively clear the previous state.

I'll go with a more manual approach, just a simple text field for the ACF and encode into the template to use this slug.  Hope it gets fixed soon!

**Comment by siawaahmed** [comment]
i am having same issue any solution ?

**Comment by rafaelcmrj** [comment]
@Diesector @siawaahmed I'm having same problem.. did you guys fixed it ?
